CREATE DATABASE IF NOT EXISTS `hrm`
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;
USE `hrm`;

CREATE TABLE IF NOT EXISTS departments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS positions(
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(100) NOT NULL,
  base_salary DECIMAL(10,2)
);